version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: bookcar_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./bookcar_backend
    env_file:
      - ./bookcar_backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./bookcar_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: