CREATE TABLE "trainees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "date_of_birth" date,
  "gender" varchar,
  "cccd" varchar UNIQUE,
  "address" text,
  "course_id" int,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "instructors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "license_number" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "vehicles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plate" varchar UNIQUE,
  "branch_id" int,
  "notes" text,
  "device_id" varchar,
  "model" varchar,
  "manufacture_year" int,
  "last_updated" timestamp,
  "hang" varchar,
  "gptl" varchar,
  "state" varchar,
  "owner" varchar,
  "synced" boolean,
  "sync_error" text,
  "type" varchar,
  "color" varchar,
  "gptl_expired_date" date,
  "status" varchar,
  "created_date" timestamp,
  "updated_date" timestamp,
  "created_by" varchar,
  "updated_by" varchar
);

CREATE TABLE "branches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "short_name" varchar,
  "province_id" int,
  "customer_id" int,
  "config" json,
  "created_date" timestamp,
  "updated_date" timestamp,
  "created_by" varchar,
  "updated_by" varchar
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_giao_dich" varchar,
  "ma_dv_gui" varchar,
  "ten_dv_gui" varchar,
  "ngay_gui" timestamp,
  "nguoi_gui" varchar,
  "tong_so_ban_ghi" int,
  "ma_bci" varchar,
  "ma_so_gtvt" varchar,
  "ten_so_gtvt" varchar,
  "ma_csdt" varchar,
  "ten_csdt" varchar,
  "ma_khoa_hoc" varchar,
  "ten_khoa_hoc" varchar,
  "ma_hang_dao_tao" varchar,
  "hang_gplx" varchar,
  "so_bci" varchar,
  "ngay_bci" timestamp,
  "luu_luong" int,
  "so_hoc_sinh" int,
  "ngay_khai_giang" timestamp,
  "ngay_be_giang" timestamp,
  "so_qd_kg" varchar,
  "ngay_qd_kg" timestamp,
  "ngay_sat_hach" timestamp,
  "thoi_gian_dt" int,
  "so_qdkt" varchar,
  "ddkt" varchar,
  "so_qdtt" varchar,
  "status" int,
  "card_status" int,
  "stats" json,
  "branch_id" int,
  "synced" boolean,
  "sync_error" text,
  "created_date" timestamp,
  "updated_date" timestamp,
  "created_by" varchar,
  "updated_by" varchar
);

ALTER TABLE "trainees" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "vehicles" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
