from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, JSON, ForeignKey
from sqlalchemy.sql import func
from app.database import Base

class Course(Base):
    __tablename__ = "courses"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ma_giao_dich = Column(String)
    ma_dv_gui = Column(String)
    ten_dv_gui = Column(String)
    ngay_gui = Column(DateTime)
    nguoi_gui = Column(String)
    tong_so_ban_ghi = Column(Integer)
    ma_bci = Column(String)
    ma_so_gtvt = Column(String)
    ten_so_gtvt = Column(String)
    ma_csdt = Column(String)
    ten_csdt = Column(String)
    ma_khoa_hoc = Column(String)
    ten_khoa_hoc = Column(String)
    ma_hang_dao_tao = Column(String)
    hang_gplx = Column(String)
    so_bci = Column(String)
    ngay_bci = Column(DateTime)
    luu_luong = Column(Integer)
    so_hoc_sinh = Column(Integer)
    ngay_khai_giang = Column(DateTime)
    ngay_be_giang = Column(DateTime)
    so_qd_kg = Column(String)
    ngay_qd_kg = Column(DateTime)
    ngay_sat_hach = Column(DateTime)
    thoi_gian_dt = Column(Integer)
    so_qdkt = Column(String)
    ddkt = Column(String)
    so_qdtt = Column(String)
    status = Column(Integer)
    card_status = Column(Integer)
    stats = Column(JSON)
    branch_id = Column(Integer, ForeignKey("branches.id"))
    synced = Column(Boolean, default=False)
    sync_error = Column(Text)
    created_date = Column(DateTime, default=func.now())
    updated_date = Column(DateTime, default=func.now(), onupdate=func.now())
    created_by = Column(String)
    updated_by = Column(String)
