"""Adding vehicle_plate for Participants

Revision ID: 5c1f870abbe8
Revises: 7e1712c08917
Create Date: 2025-05-26 13:49:31.128148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1f870abbe8'
down_revision: Union[str, None] = '7e1712c08917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_lesson_participants', sa.Column('vehicle_plate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_lesson_participants', 'vehicle_plate')
    # ### end Alembic commands ###
