"""Adding hang_gplx for Driving Lesson

Revision ID: 7e1712c08917
Revises: 97da845e6966
Create Date: 2025-05-26 10:55:33.285187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1712c08917'
down_revision: Union[str, None] = '97da845e6966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_lessons', sa.Column('hang_gplx', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_lessons', 'hang_gplx')
    # ### end Alembic commands ###
