"""add time window and actual time fields to driving_lesson

Revision ID: 8fb32510c68a
Revises: 45ed6360b382
Create Date: 2025-05-21 10:53:37.993576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb32510c68a'
down_revision: Union[str, None] = '45ed6360b382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_lesson_participants', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.add_column('driving_lesson_participants', sa.Column('actual_end_time', sa.DateTime(), nullable=True))
    op.add_column('driving_lessons', sa.Column('start_time_window', sa.DateTime(), nullable=True))
    op.add_column('driving_lessons', sa.Column('end_time_window', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_lessons', 'end_time_window')
    op.drop_column('driving_lessons', 'start_time_window')
    op.drop_column('driving_lesson_participants', 'actual_end_time')
    op.drop_column('driving_lesson_participants', 'actual_start_time')
    # ### end Alembic commands ###
