"""Change nullable trainee_id in Participants Table

Revision ID: 97da845e6966
Revises: 37284d6041bd
Create Date: 2025-05-26 10:48:36.418323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97da845e6966'
down_revision: Union[str, None] = '37284d6041bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driving_lesson_participants', 'trainee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driving_lesson_participants', 'trainee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
