"""Create Vehicle and Branch

Revision ID: a685b1b1b1a4
Revises: 
Create Date: 2025-05-19 15:12:42.840321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a685b1b1b1a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('branches', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('branches', sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('branches', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_column('branches', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('branches', 'updated_by')
    op.drop_column('branches', 'created_by')
    op.drop_column('branches', 'updated_date')
    op.drop_column('branches', 'created_date')
    op.drop_column('branches', 'config')
    op.drop_column('branches', 'customer_id')
    op.drop_column('branches', 'short_name')
    # ### end Alembic commands ###
