"""update trainees table structure

Revision ID: cecf1e1fa865
Revises: 3faaf7fc5edb
Create Date: 2025-05-20 10:52:46.699785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cecf1e1fa865'
down_revision: Union[str, None] = '3faaf7fc5edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainees', 'so_tt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trainees', 'ngay_sinh',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint('trainees_cccd_key', 'trainees', type_='unique')
    op.drop_constraint('trainees_email_key', 'trainees', type_='unique')
    op.drop_column('trainees', 'created_at')
    op.drop_column('trainees', 'name')
    op.drop_column('trainees', 'phone')
    op.drop_column('trainees', 'cccd')
    op.drop_column('trainees', 'gender')
    op.drop_column('trainees', 'updated_at')
    op.drop_column('trainees', 'date_of_birth')
    op.drop_column('trainees', 'address')
    op.drop_column('trainees', 'email')
    op.drop_column('trainees', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('cccd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trainees', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('trainees_email_key', 'trainees', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('trainees_cccd_key', 'trainees', ['cccd'], postgresql_nulls_not_distinct=False)
    op.alter_column('trainees', 'ngay_sinh',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('trainees', 'so_tt',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
