"""Add state column to driving_lesson_participants

Revision ID: d28a7db027ea
Revises: 5c1f870abbe8
Create Date: 2025-05-29 15:19:22.309374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28a7db027ea'
down_revision: Union[str, None] = '5c1f870abbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_lesson_participants', sa.Column('state', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_lesson_participants', 'state')
    # ### end Alembic commands ###
