"""add courses table

Revision ID: ed3c98397cec
Revises: 53a708cddb16
Create Date: 2025-05-20 10:34:07.955894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3c98397cec'
down_revision: Union[str, None] = '53a708cddb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_giao_dich', sa.String(), nullable=True),
    sa.Column('ma_dv_gui', sa.String(), nullable=True),
    sa.Column('ten_dv_gui', sa.String(), nullable=True),
    sa.Column('ngay_gui', sa.DateTime(), nullable=True),
    sa.Column('nguoi_gui', sa.String(), nullable=True),
    sa.Column('tong_so_ban_ghi', sa.Integer(), nullable=True),
    sa.Column('ma_bci', sa.String(), nullable=True),
    sa.Column('ma_so_gtvt', sa.String(), nullable=True),
    sa.Column('ten_so_gtvt', sa.String(), nullable=True),
    sa.Column('ma_csdt', sa.String(), nullable=True),
    sa.Column('ten_csdt', sa.String(), nullable=True),
    sa.Column('ma_khoa_hoc', sa.String(), nullable=True),
    sa.Column('ten_khoa_hoc', sa.String(), nullable=True),
    sa.Column('ma_hang_dao_tao', sa.String(), nullable=True),
    sa.Column('hang_gplx', sa.String(), nullable=True),
    sa.Column('so_bci', sa.String(), nullable=True),
    sa.Column('ngay_bci', sa.DateTime(), nullable=True),
    sa.Column('luu_luong', sa.Integer(), nullable=True),
    sa.Column('so_hoc_sinh', sa.Integer(), nullable=True),
    sa.Column('ngay_khai_giang', sa.DateTime(), nullable=True),
    sa.Column('ngay_be_giang', sa.DateTime(), nullable=True),
    sa.Column('so_qd_kg', sa.String(), nullable=True),
    sa.Column('ngay_qd_kg', sa.DateTime(), nullable=True),
    sa.Column('ngay_sat_hach', sa.DateTime(), nullable=True),
    sa.Column('thoi_gian_dt', sa.Integer(), nullable=True),
    sa.Column('so_qdkt', sa.String(), nullable=True),
    sa.Column('ddkt', sa.String(), nullable=True),
    sa.Column('so_qdtt', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('card_status', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('branches', 'province_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('province_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('courses')
    # ### end Alembic commands ###
